OnlineShopping/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShopping.Data;
using OnlineShopping.Models;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ProductsController : Controller
    {
        private ApplicationDbContext _db;
        private IHostingEnvironment _he;

        public ProductsController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }
        public IActionResult Index()
        {
            return View(_db.Products.Include(c => c.ProductTypes).Include(f => f.SpecialTags).ToList());
        }

        [HttpPost]
        //POST Index action method
        public IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            if (lowAmount == null || largeAmount == null)
            {
                products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).ToList();
            }
            return View(products);
        }


        public ActionResult Create()
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Create Post Action Method
        public async Task<IActionResult> Create(Products products, IFormFile image)
        {
            if (image != null)
            {
                var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                await image.CopyToAsync(new FileStream(name, FileMode.Create));
                products.Image = "Images/" + image.FileName;
            }
            if (image == null)
            {
                products.Image = "Images/noimage.jpeg";
            }
            if (ModelState.IsValid)
            {
                var searchProduct = _db.Products.FirstOrDefault(c => c.Name == products.Name);
                if (searchProduct != null)
                {
                    ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
                    ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
                    ViewBag.message = "This product is already exist";

                    return View(products);
                }
                _db.Products.Add(products);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product has been saved";
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }
        //Edit Get Action Method
        public ActionResult Edit(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");

            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c=>c.ProductTypes).Include(f=>f.SpecialTags).ToList().FirstOrDefault(c=>c.Product==id);
            if (product == null)
            {
                return NotFound();
            }


            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Create Post Action Method
        public async Task<IActionResult> Edit(Products products, IFormFile image)
        {
            if (image != null)
            {
                var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                await image.CopyToAsync(new FileStream(name, FileMode.Create));
                products.Image = "Images/" + image.FileName;
            }
            if (image == null)
            {
                products.Image = "Images/noimage.jpeg";
            }
            if (ModelState.IsValid)
            {
                _db.Products.Update(products);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product has been saved";
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }
        //Details Get Action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(f => f.SpecialTags).ToList().FirstOrDefault(c => c.Product == id);
            if (product == null)
            {
                return NotFound();
            }


            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Details Post Action Method
        public IActionResult Details(Products products)
        {

            return RedirectToAction(nameof(Index));

        }
        //Delete Get Action Method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(f => f.SpecialTags).ToList().Where(c => c.Product == id).FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }


            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Delete Post Action Method
        public async Task<IActionResult> Delete(int id, Products products)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != products.Product)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(f => f.SpecialTags).ToList().FirstOrDefault(c => c.Product == id);
            if (product == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(product);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product deleted";
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }
    }
}

OnlineShopping/Areas/Admin/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineShopping.Areas.Admin.Models;
using OnlineShopping.Data;

namespace OnlineShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        ApplicationDbContext _db;
        public RoleController(RoleManager<IdentityRole>roleManager,ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _db = db;

            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            ViewBag.Roles = roles;
            return View();
        }

        public async Task<IActionResult>Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult>Create(string name)
        {
            IdentityRole role = new IdentityRole();
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if(isExist)
            {
                ViewBag.mgs = "This role is aldeady exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.CreateAsync(role);
            if(result.Succeeded)
            {
                TempData["save"] = "Role has been saved successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        public async Task<IActionResult> Edit(string id)
        {
            var role =await _roleManager.FindByIdAsync(id);
            if(role==null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id,string name)
        {
            
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.mgs = "This role is aldeady exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                TempData["save"] = "Role has been updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult>DeleteConfirm(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            var result =await _roleManager.DeleteAsync(role);
            if(result.Succeeded)
            {
                TempData["delete"] = "Role has been deleted successfully";
                return RedirectToAction(nameof(Index));
            }            
            return View();
        }


        public async Task<IActionResult>Assign()
        {
            
            ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
            ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Assign(RoleUserVm roleUser)
        {
            var user = _db.ApplicationUsers.FirstOrDefault(c => c.Id == roleUser.UserId);
            var isCheckRoleAssign =await _userManager.IsInRoleAsync(user, roleUser.RoleId);
            if(isCheckRoleAssign)
            {
                ViewBag.mgs = "This user already assign this role.";
                ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
                ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
                return View();
            }
            var role = await _userManager.AddToRoleAsync(user,roleUser.RoleId);
            if(role.Succeeded)
            {
                TempData["save"] = "User Role assigned.";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public ActionResult AssignUserRole()
        {
            var result = from ur in _db.UserRoles
                         join r in _db.Roles on ur.RoleId equals r.Id
                         join a in _db.ApplicationUsers on ur.UserId equals a.Id
                         select new UserRoleMaping()
                         {
                             UserId=ur.UserId,
                             RoleId=ur.RoleId,
                             UserName=a.UserName,
                             RoleName=r.Name
                         };
            ViewBag.UserRoles = result;
            return View();
        }


    }
}

OnlineShopping/Areas/Admin/Controllers/SpecialTagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShopping.Data;
using OnlineShopping.Models;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SpecialTagsController : Controller
    {
        private ApplicationDbContext _db;

        public SpecialTagsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //var data = _db.ProductTypes.ToList();
            return View(_db.SpecialTags.ToList());
        }

        //Create Get Action Method
        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Create Post Action Method
        public async Task<IActionResult> Create(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                _db.SpecialTags.Add(specialTags);
                await _db.SaveChangesAsync();
                TempData["save"] = "Special tag has been saved";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }

        //Edit Get Action Method
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTags = _db.SpecialTags.Find(id);
            if (specialTags == null)
            {
                return NotFound();
            }


            return View(specialTags);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Create Post Action Method
        public async Task<IActionResult> Edit(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                _db.Update(specialTags);
                await _db.SaveChangesAsync();
                TempData["save"] = "Special tag edited";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }
        //Details Get Action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }


            return View(specialTag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Details Post Action Method
        public IActionResult Details(SpecialTags specialTags )
        {

            return RedirectToAction(nameof(Index));

        }
        //Delete Get Action Method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }


            return View(specialTag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Delete Post Action Method
        public async Task<IActionResult> Delete(int id, SpecialTags specialTags)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != specialTags.Id)
            {
                return NotFound();
            }
            var specialTag = _db.SpecialTags.Find(id);
            if ( specialTag== null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(specialTag);
                await _db.SaveChangesAsync();
                TempData["save"] = "Special tag deleted";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTag);
        }
    }
}

OnlineShopping/Views/Shared/_ButtonPartial.cshtml
@model int 
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<head>
<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
</head>
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductTypes" class="btn btn-primary" asp-route-id="@Model"> <i class="fa fa-pen"></i></a>
        <a asp-action="Details" asp-controller="ProductTypes" class="btn btn-success" asp-route-id="@Model"><i class="fa fa-list"></i></a>
        <a asp-action="Delete" asp-controller="ProductTypes" class="btn btn-danger" asp-route-id="@Model"><i class="fa fa-trash"></i></a>
    </div>
</td>

OnlineShopping/Views/Shared/_ButtonPartialProduct.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<head>
    <script src="https://kit.fontawesome.com/0b22872ed8.js" crossorigin="anonymous"></script>
</head>
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="Products" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="Products" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" asp-controller="Products" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

OnlineShopping/Views/Shared/_ButtonPartialProductTypes.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<head>
    <script src="https://kit.fontawesome.com/0b22872ed8.js" crossorigin="anonymous"></script>
</head>
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductTypes" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="ProductTypes" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" asp-controller="ProductTypes" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

OnlineShopping/Views/Shared/_ButtonPartialSpecialTags.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<head>
    <script src="https://kit.fontawesome.com/0b22872ed8.js" crossorigin="anonymous"></script>
</head>
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="SpecialTags" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="SpecialTags" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" asp-controller="SpecialTags" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

OnlineShopping/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using OnlineShopping.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
    {
        products = new List<Products>();
    }
    count = products.Count();
}
<head>
<script src="https://kit.fontawesome.com/0b22872ed8.js" crossorigin="anonymous"></script>
</head>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShopping</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.css"></link>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css"></link>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <style>
        .error{
            color:red;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">OnlineShopping</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if(userRole=="Super user")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Type</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Special Tag</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Role" asp-action="Assign">Assign</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Role" asp-action="AssignUserRole">Assign User Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">
                               <i class="fas fa-shopping-cart"></i>
                               (@count)
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineShopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

OnlineShopping/Views/Shared/_PartialView.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<head>
    <script src="https://kit.fontawesome.com/0b22872ed8.js" crossorigin="anonymous"></script>
</head>
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="User" class="btn btn-primary" asp-route-id="@Model"> <i class="fa fa-pen"></i></a>
        <a asp-action="Details" asp-controller="User" class="btn btn-success" asp-route-id="@Model"><i class="fa fa-list"></i></a>
        <a asp-action="Locout" asp-controller="User" class="btn btn-danger" asp-route-id="@Model"><i class="fa fa-trash"></i></a>
    </div>
</td>